version: '2'
services:
    blog2-app:
        image: blog2
        external_links:
            - blog2-postgresql:postgresql
            - blog2-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/blog2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    blog2-postgresql:
        extends:
            file: postgresql.yml
            service: blog2-postgresql
    blog2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: blog2-elasticsearch
